global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: /metrics

  - job_name: 'python-agent'
    static_configs:
      - targets: ['pyagent:8000']
    metrics_path: /metrics


