apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trailblip-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  tls:
    - hosts:
        - example.com
      secretName: trailblip-tls
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trailblip-backend
                port:
                  number: 80
          - path: /py/
            pathType: Prefix
            backend:
              service:
                name: trailblip-pyagent
                port:
                  number: 80

