apiVersion: v1
kind: Service
metadata:
  name: trailblip-backend
spec:
  selector:
    app: trailblip-backend
    color: blue
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: trailblip-pyagent
spec:
  selector:
    app: trailblip-pyagent
    color: blue
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

